news/urls.py
from . import views
from django.conf.urls import url,include
from django.contrib.auth import views as auth_view

app_name = 'news'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/category/$', views.CategoryView.as_view(), name='category'),
    url(r'^search/$',views.SearchResultView.as_view(),name='search_result')
    ]

newsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.flatpages.views import flatpage

# Your other patterns here

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('news.urls')),
    url(r'^user/',include('user.urls')),
    url(r'^widgets/',include('widgets.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls',)),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^accounts/', include('allauth.urls'))


]

user/urls.py
from . import views
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^profile/$', views.UpdateView.as_view(), name='profile'),
    url(r'^setpassword/', views.UpdatePasswordView.as_view(), name='set_password'),


    url(r'^oauth/', include('social_django.urls', namespace='social')),

    url(r'^password_reset/$', auth_views.password_reset,
        {'template_name': 'registration/pswd_reset_form.html'}, name='password_reset'),

    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registration/pswd_reset_done.html', }, name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})',
        auth_views.password_reset_confirm,
        {'template_name': 'registration/pswd_reset_confirm.html', }, name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'registration/pswd_reset_complete.html'}, name='password_reset_complete')

]

news/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.contrib.auth.models import User, AbstractUser


class Category(models.Model):
    category_name=models.CharField(max_length=100)
    def __str__(self):
        return self.category_name

class News(models.Model):
    title= models.CharField(max_length=200)
    content=models.CharField(max_length=750)
    author=models.CharField(max_length=200)
    category = models.ForeignKey(Category,on_delete=models.CASCADE ,blank=True, null=True)
    pub_date = models.DateTimeField()

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.title



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

news/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

news/views.py
from django.views import generic
from django.views.generic import ListView

from .models import News,Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = 'latest_news_list'
    paginate_by = 3

    def get_queryset(self):
        return News.objects.all()

    def get_context_data(self):
        context = super().get_context_data()
        category_list = Category.objects.all()
        context['category_list']= category_list
        return  context



class DetailView(generic.DetailView):
    model = News
    template_name = 'news/detail.html'


class CategoryView(generic.ListView):
    model=Category
    template_name='news/category.html'
    context_object_name = 'list'
    paginate_by = 3
    def get_queryset(self):
        pk = self.kwargs.get('pk', 'lat')
        if pk != 'lat':
            cat = self.model._default_manager.get(pk=int(pk))
            return cat.news_set.all()
        else:
            return self.model._default_manager.all()




class SearchResultView(generic.ListView):
    """ class view to display list of news  on the page """
    model = News
    template_name = 'news/search_result.html'
    context_object_name = 'news'
    paginate_by = 3


    def get_queryset(self,*args,**kwargs):
        return News.objects.filter(title__icontains = self.request.GET['searchitem'])
        #TODO: try catch

    def get_context_data(self):
        # Call the base implementation first to get a context
        context = super().get_context_data()
        category_list = Category.objects.all()
        context['category_list'] = category_list
        return context

news/templates/news/base.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'news/style.css' %}">
         <style>
  .affix {
      top: 0;
      width: 100%;
      z-index:1;
  }

  .affix + .container-fluid {
      padding-top: 70px;
  }
  </style>
    </head>
    <body>
        <div class="container_fluid">
        <div class="head">
             <div class="row">
               <div class="col-md-8">
                   <h1>The News Reporter</h1></div>


        <div class="col-md-4 col-md-offset-8">
            <form action="{% url 'news:search_result' %}" method="get" class="search-form">
                <div class="form-group has-feedback">
            		<label for="searchitem" class="sr-only">Search</label>

            		<input type="text" class="form-control" name="searchitem" id="searchitem" placeholder="search">
              		<span class="glyphicon glyphicon-search form-control-feedback"></span>
            	</div>
            </form>
        </div>
    </div>
</div>

        </div>
            <nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="158">
                <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{%url 'news:index' %}">The News Reporter</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{%url 'news:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Page 1-1</a></li>
                            <li><a href="#">Page 1-2</a></li>
                            <li><a href="#">Page 1-3</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Page 2</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'profile' %}">Hi {{ user.username }}!</a></li>
                    <li><a href="{% url 'logout' %}">logout</a>  </li>


                        {% else %}


                    <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif%}
                </ul>
            </div>
            </nav>
        </div>
        <div class="bo">
    {% block content %}

    {% endblock%}
            </div>
    </body>
</html>

news/templates/news/category.html
{% extends "news/index.html" %}
{% block news %}
        <ul>
        {% for n in list %}
            <div class="news_headings">
            <li><h2><a href="{% url 'news:detail' n.id %}">{{ n.title }}</a></h2></li>
            <p>{{n.content|truncatechars_html:200}} <a href="{% url 'news:detail' n.id %}">more</a></p>

            </div>
        {% endfor%}

        </ul>

              {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

        {% block footer %}
        {% endblock %}

news/templates/news/detail.html
{% extends "news/home.html" %}
<<<<<<< HEAD
{% load social_share %}
=======

>>>>>>> c5096056dabd440f0226e27b475a214e02beef9b

{% block content %}
{% load comments %}
<head>
    <style>
        #comment_form {
                    margin: 20px 400px 20px 20px ;
                    color:blue;
            }

            #id_submit{
                    background-color: rgba(0,131,143 ,1);
                      }

    </style>
<div class="container news_headings">
    <ul list-style-type="none">
        <li><h2>{{ news.title }}</h2></li>
        <li><p>{{ news.content }}</p></li>
    </ul>
<<<<<<< HEAD
    {% post_to_facebook news.news_id %}
    {% post_to_gplus www.google.com %}

    {% post_to_twitter "News: {{news.title}}. Check it out!" news.news_id "Post to Twitter" %}
    {% post_to_linkedin news.title news.news_id "Post to LinkedIn" %}
</div>
    <div class="news_headings"><h2>Comment here</h2></div>
=======
</div>
    <div class="news_headings"><h2>Comment here</h2></div>

>>>>>>> c5096056dabd440f0226e27b475a214e02beef9b
    {% if user.is_authenticated %}
    {% get_comment_form for news as form %}
    <div id="comment_form">
    <form id="form" action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}

    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="submit" value="Add comment" id="id_submit" />

    </form>
        <br />
    </div>

{% else %}
    <p>Please <a href="{% url 'login' %}">log in</a> to leave a comment.</p>
{% endif %}

  <div id="commentlist">
    {% get_comment_list for news as comment_list %}
    {% if comment_list %}
        {% get_comment_count for news as comment_count %}

    <div class="news_headings"><p>This news has {{ comment_count }} comments.</p></div>

    {% for comment in comment_list %}
    <div class="news_headings">
        <h2>{{comment.comment}}</h2> <br/>
       <p>posted by:{{ comment.user_name }} at {{ comment.submit_date}}</p></div>
    {% endfor %}
    {% else %}
    <p>----no cooments----</p>
{%endif%}
  </div>
         <script type="text/javascript" charset="utf-8">
                  function bindPostCommentHandler() {
                      $('#comment_form form input.submit-preview').remove();
                      $('#comment_form form').submit(function() {
                          $.ajax({
                              type: "POST",
                             data: $('#comment_form form').serialize(),
                              url: "{% comment_form_target %}",
                              cache: false,
                             dataType: "html",
                             success: function(html, textStatus) {
                                  $("#commentlist").load("{% url 'refresh_post' news.id %}");
                                    $("#form")[0].reset();

                             },
                             error: function (XMLHttpRequest, textStatus, errorThrown) {
                                 $('#comment_form form').replaceWith('Your comment was unable to be posted at this time.  We apologise for the inconvenience.');
                             }
                         });
                         return false;
                     });
                 }

                 $(document).ready(function() {
                     bindPostCommentHandler();
                 });
                </script>

{% endblock %}


{% block footer %}
        {% endblock %}

news/templates/news/home.html
{% load static %}
<html>
	<head>
		<title>Projection by TEMPLATED</title>
		 <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="{% static 'news/main.css' %}" />
		        <link rel="stylesheet" href="{% static 'news/style.css' %}">


		<style>
  			.affix {
      		top: 0;
     		 width: 100%;
     		 z-index:5;
  			}
		</style>

<body>
	</head>
	<div class="row">
<div class="cotainer-fluid afix">
	<nav class="navbar navbar-inverse" data-spy="affix">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="{%url 'news:index' %}">The News Reporter</a>
			</div>
			<ul class="nav navbar-nav">
				<li class="active"><a href="{%url 'news:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
				<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="#">Page 1-1</a></li>
				<li><a href="#">Page 1-2</a></li>
				<li><a href="#">Page 1-3</a></li>
			</ul>
				</li>
				<li><a href="#">Page 2</a></li>
			</ul>


			<ul class="nav navbar-nav navbar-right">

				<li>
					<form action="/search/" method="get" class="search-form">
                		<div class="form-group has-feedback">
            				<label for="searchitem" class="sr-only">Search</label>

            				<input type="text" class="form-control" name="searchitem" id="searchitem" placeholder="search">
              				<span class="glyphicon glyphicon-search form-control-feedback"></span>
            			</div>
            		</form>
				</li>
				<li>
				{% if user.is_authenticated %}
					<li><a href="{% url 'profile' %}">Hi {{ user.username }}!</a></li>
					<li><a href="{% url 'logout' %}">logout</a>  </li>
				{% else %}
					<li><a href="/user/signup/#footersignup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
					<li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
				{% endif%}
				</li>
			</ul>



		</div>
	</nav>

</div>
</div>


	{% block banner %}
		<!-- Banner -->
	<div class="row">
		<div class="col-md-12 bo">

			<section id="banner">




				<div class="inner">
					<header>
						<h1>The News Reporter</h1>
					</header>

					<div class="flex ">

						<div>
							<span class="icon fa-car"></span>
							<h3><a href="{% url 'profile' %}">About Us</a></h3>
						</div>

						<div>
							<span class="icon fa-camera"></span>
							<h3><a href="{% url 'contact' %}">Contact Us</a></h3>

						</div>

						<div>
							<span class="icon fa-bug"></span>
							<h3><a href="{% url 'subscribe' %}">Subscribe</a></h3>

						</div>

					</div>


				</div>
		</div></div>
			</section>
			{% endblock %}


				{% block content %}

			{% endblock %}
		<!-- F%%ooter -->

			{% block footer %}



<div class="padding-top-fiftheen-px"></div>
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
          <a href="#" class="footerlink" rel="index,follow" title="Header 1">Header 1</a>
          <p class="text-muted small padding-top-fiftheen-px">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <div class="align-text-right hidden-lg hidden-md hidden-sm">
            <a href="#" id="ButtonLink" class="btn btn-warning btn-sm">more<i class="fa fa-chevron-right padding-left-five-px"></i></a>
            <div class="clearfix"></div>
            <hr class="color-white">
            <div class="mouse-help"></div>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
          <a href="#" class="footerlink" rel="follow" title="Header 2">Header 2</a>
          <p class="text-muted small padding-top-fiftheen-px">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <div class="align-text-right hidden-lg hidden-md hidden-sm">
            <a href="#" id="ButtonLink" class="btn btn-warning btn-sm">more<i class="fa fa-chevron-right padding-left-five-px"></i></a>
            <div class="clearfix"></div>
            <hr class="color-white">
            <div class="mouse-help"></div>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
          <a href="#" class="footerlink" rel="follow" title="Header 3">Header 3</a>
          <p class="text-muted small padding-top-fiftheen-px">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <div class="align-text-right hidden-lg hidden-md hidden-sm">
            <a href="#" id="ButtonLink" class="btn btn-warning btn-sm">more<i class="fa fa-chevron-right padding-left-five-px"></i></a>
            <div class="clearfix"></div>
            <div class="mouse-help"></div>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-xs-12 clearfix hidden-lg hidden-md">
        <div class="padding-top-fiftheen-px"></div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 column text-center">
        <span class="social-sharing">Connect & Share</span>
        <div class="clearfix hidden-md hidden-sm hidden-xs padding-top-fiftheen-px"></div>
        <div class="clearfix hidden-lg hidden-md hidden-sm padding-top-ten-px"></div>
        <div class="clearfix hidden-lg hidden-xs">
          <hr class="primary">
        </div>

        <div class="col-lg-12 text-center clearfix">
          <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 no-padding">
            <div class="col-sm-6 col-xs-6"><a href="https://www.facebook.com/@PartnerFacebook" title="Share on Facebook" class="social-sharing" target="_blank"><i class="fa fa-2x fa-facebook-square"></i></a></div>
            <div class="col-sm-6 col-xs-6"><a href="https://twitter.com/@PartnerTwitterHandle" title="Share on Twitter" class="social-sharing" target="_blank"><i class="fa fa-2x fa-twitter-square"></i></a></div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 no-padding">
            <div class="col-sm-6 col-xs-6"><a href="https://www.instagram.com/@PartnerInstagram" title="Share on Instagram" rel="index,follow" class="social-sharing" target="_blank"><i class="fa fa-2x fa-instagram"></i></a></div>
            <div class="col-sm-6 col-xs-6"><a href="https://www.linkedin.com/company/@PartnerLinkedIn" title="Share on LinkedIn" rel="index,follow" class="social-sharing" target="_blank"><i class="fa fa-2x fa-linkedin-square"></i></a></div>
          </div>
          <div class="col-sm-12 col-xs-12 clearfix hidden-lg hidden-md hidden-sm padding-top-eight-px"></div>
          <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 no-padding">
            <div class="col-sm-6 col-xs-6"><a href="https://www.pinterest.com/@PartnerPinterest" title="Share on Pinterest" rel="index,follow" class="social-sharing" target="_blank"><i class="fa fa-2x fa-pinterest-square"></i></a></div>
            <div class="col-sm-6 col-xs-6"><a href="https://www.youtube.com/" title="Share on YouTube" rel="index,follow" class="social-sharing" target="_blank"><i class="fa fa-2x fa-youtube-square"></i></a></div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 no-padding">
            <div class="col-sm-6 col-xs-6"><a href="https://play.google.com/store/apps/details?id=com.propay.mobile" title="Download from Google Play" rel="index,follow" class="social-sharing" target="_blank"><i class="fa fa-2x fa-android"></i></a></div>
            <div class="col-sm-6 col-xs-6"><a href="https://itunes.apple.com/us/app/propay-accept-credit-cards/id433046878?mt=8" rel="index,follow" title="Download from Apple Store" class="social-sharing" target="_blank"><i class="fa fa-2x fa-apple"></i></a></div>
          </div>
        </div>

      </div>
    </div>
    <hr>
    <div class="col-lg-12 col-md-12 no-padding">
      <div class="copyright">
						&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
					</div>

  </div>
</footer>
{% endblock %}

</div>

</body>
</html>

news/templates/news/index.html
{% extends "news/home.html" %}
{% block content %}

    <div class="row">
        <div class="col-md-9">
            {% block news %}
                {% if latest_news_list %}
                    <ul >
                        {% for n in latest_news_list %}
                            <div class="news_headings">
                                <li><h2><a href="{% url 'news:detail' n.id %}">{{ n.title }}</a></h2></li>
                                <p>{{n.content|truncatechars_html:200}} <a href="{% url 'news:detail' n.id %}">more</a></p>
                            </div>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p>No news are available.</p>
                {% endif %}

              {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

                </div>


            {% endblock %}

            <div class="col-md-3">
                <div class="news_cat">
                <ul>
                    {% for i in category_list%}

                        <li><h4><a href="{% url 'news:category' i.id %} ">{{i.category_name|capfirst}}</a></h4></li>
                    {% endfor %}
                </ul>

                </div>
        </div>
    </div>
{% endblock %}

news/templates/news/list.html
{% for news in latest_news_list %}
    {# Each "news" is a News model object. #}
    {{ news.title }}<br />
    ...
{% endfor %}


{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

news/templates/news/search_result.html
{% extends "news/home.html" %}
{% block content %}

<div class="row">
    <div class="col-md-10">
        {% if news %}
            <ul >
                {% for n in news %}
                    <div class="news_headings">
                        <li><h2><a href="{% url 'news:detail' n.id %}">{{ n.title }}</a></h2></li>
                        <p>{{n.content|truncatechars_html:200}} <a href="{% url 'news:detail' n.id %}">more</a></p>
                    </div>
                {% endfor %}
            </ul>
        {% else %}
            <p>No news are available.</p>
        {% endif %}
          {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

                 </div>
</div>
{% endblock %}

{% block footer %}
        {% endblock %}

news/templates/news/signup.html
{% extends "news/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'news/loginstyle.css' %}">
<div class="container">
    <div class="row">
        <div class="page-header"><h2>Sign-up</h2></div>

        <fieldset>

            <!-- Form Name -->
            <legend><a href="{% url 'news:login' %}">Already have an account?</a></legend>

            <!-- Text input-->
            <div class="form-group">
                <form class="form-horizontal" method="post" >
                    {% csrf_token %}
                    {% for field in form %}

                    <div class="tag1 col-md-4">
                        {{ field.label_tag }}</div>
                    <div class="tag2 col-md-6">{{ field }}</div>

                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}

                    {% endfor %}
                    <div class="col-md-4">
                        <button type="submit" class="btn btn-block button">Sign up</button></div>
                </form>
            </div>
        </fieldset>

    </div> <!--./row -->
</div> <!--./container -->


{% endblock %}